const { REACT_APP_HASURA_GRAPH_URL, REACT_APP_HASURA_ADMIN_SECRET } =  process.env;

export default {
  HASURA_GRAPH_URL: REACT_APP_HASURA_GRAPH_URL,
  HASURA_ADMIN_SECRET: REACT_APP_HASURA_ADMIN_SECRET,
}
